framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: app.another_bus
        envelope:
            sender: '%env(MAIL_FROM)%'
        headers:
            From: '%env(SOCIETE)% <%env(MAIL_FROM)%>'
