twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        societe: '%societe%'
        address: '%address%'
        siret: '%siret%'
        societe_acronyme: '%societe_acronyme%'

when@test:
    twig:
        strict_variables: true
